name: 问题反馈
description: 反馈出现的问题
title: '[BUG]: '
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ##  提交问题前请先注意以下事项
        + 如无特殊情况，请使用**最新版本**的脚本。
        + 确保你的浏览器和用户脚本管理器是最新版本。
        + 请先查看[常见问题](README.md#常见问题)是否有解决方案。
  - type: input
    id: version
    attributes:
      label: 脚本版本
      placeholder: 1.6.1
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 浏览器
      placeholder: Chome
    validations:
      required: true
  - type: input
    id: userscript-manager
    attributes:
      label: 用户脚本管理器
      placeholder: Tampermonkey, Greasemonkey, Stay
      value: Tampermonkey
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 出现问题的网址
      description: 提供出现问题的网页链接
      placeholder: https://bilibili.com/....
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 描述现象
      description: 简短描述出现的问题现象
      placeholder: 请输入问题的简短描述
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: 如何复现
      description: 如果需要一定的操作步骤才能复现问题，请在此处描述。
      placeholder: |-
        1. 进入 '...' 网址
        2. 点击 '....'
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如有截图，请在此处粘贴或上传。
      placeholder: 粘贴或上传截图。
