---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Build
        run: |
          pnpm build

      - name: Check if tag contains 'beta'
        id: check_tag
        run: echo "::set-output name=beta::$(if [[ "${{ github.ref }}" == *"beta"* ]]; then echo 'true'; else echo 'false'; fi)"
        shell: bash
    
      - name: Create Release with Changelog
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
